# Generated by Django 2.0.2 on 2021-07-20 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_post'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='PostModel',
        ),
    ]
